//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityObject.Entities.EntityFromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authentication
    {
        public Authentication()
        {
            this.User_SecurityQuestion = new HashSet<User_SecurityQuestion>();
        }
    
        public int UserID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string UserMInitial { get; set; }
        public string UserName { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public int ModifiedBy { get; set; }
        public Nullable<int> OnBehalfOfBy { get; set; }
        public Nullable<int> AddressID { get; set; }
        public Nullable<bool> Deleted_Ind { get; set; }
        public string PreferredTimeZone { get; set; }
        public string PasswordHist { get; set; }
        public Nullable<bool> IsRegisterComplete { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<User_SecurityQuestion> User_SecurityQuestion { get; set; }
    }
}
