//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityObject.Entities.EntityFromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailType
    {
        public byte EmailTypeId { get; set; }
        public string EmailTypeCd { get; set; }
        public string EmailTypeDescription { get; set; }
        public Nullable<bool> Deleted_ind { get; set; }
    }
}
