//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityObject.Entities.EntityFromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public int EmailId { get; set; }
        public string EmailTo { get; set; }
        public string EmailFrom { get; set; }
        public string EmailCC { get; set; }
        public string EmailBCC { get; set; }
        public string Subject { get; set; }
        public string ContentText { get; set; }
        public string ContentHtml { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public int ModifiedBy { get; set; }
        public Nullable<int> OnBehalfOfBy { get; set; }
        public Nullable<bool> Deleted_Ind { get; set; }
        public Nullable<bool> IsSent { get; set; }
        public byte MailTypeId { get; set; }
    }
}
