//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityObject.Entities.EntityFromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityQuestion
    {
        public SecurityQuestion()
        {
            this.User_SecurityQuestion = new HashSet<User_SecurityQuestion>();
        }
    
        public int SecurityQuestionID { get; set; }
        public string SecurityQuestionDescription { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public int ModifiedBy { get; set; }
        public Nullable<bool> Deleted_Ind { get; set; }
    
        public virtual ICollection<User_SecurityQuestion> User_SecurityQuestion { get; set; }
    }
}
