//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityObject.Entities.EntityFromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_SecurityQuestion
    {
        public int User_SecurityQuestionID { get; set; }
        public int User_ID { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public int ModifiedBy { get; set; }
        public Nullable<bool> Deleted_Ind { get; set; }
        public string Answer { get; set; }
        public int SecurityQuestionID { get; set; }
    
        public virtual Authentication Authentication { get; set; }
        public virtual SecurityQuestion SecurityQuestion { get; set; }
    }
}
